### ISSUE TITLE
Create badpenny task to periodically clean away dead builds

### ISSUE THREAD

**Issue by mrrrgn** [mozilla/build-relengapi-clobberer#24]
Builds are auto-generated by slaves registering with the clobberer api. If a build goes away, it shouldn't stay in the table forever. A recurring task should be created that clears away any build with a "last_build_time" earlier than "time.time() - (3600*24*21)" i.e. 21 days

Basically, relengapi rewrite of => https://github.com/mozilla/build-tools/blob/master/clobberer/cleanup.php

**Comment by djmitche** [comment]
This issue was moved to mozilla/build-relengapi#245
